language: java
services:
  - docker
jdk:
  - openjdk16
script:
  - ./mvnw clean install
before_install:
  - chmod +x mvnw
  - docker build -t cryptoboard-coin-service:latest .
  - docker run -p 8081:8080 cryptoboard-coin-service
