language: java
jdk:
  - openjdk16
services:
  - docker
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u "$HEROKU_USERNAME" --password=$(HEROKU_TOKEN) registry.heroku.com
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: "dirklemmen"
    token: ${SONAR_TOKEN} # encrypted value of your token
jobs:
  include:
    - stage: code_quality_check
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DirkLemmen_cryptoboard-coin-service
    - stage: build_java_package
      script:
        - mvn clean package

    - stage: build_docker
      script:
        - docker build -f Dockerfile -t cryptoboard-coin-service:latest .
        - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag cryptoboard-coin-service "$DOCKER_HUB_USERNAME"/cryptoboard-coin-service
        - docker push "$DOCKER_HUB_USERNAME"/cryptoboard-coin-service

    - stage: deployment
      script:
        - heroku container:push web -a cryptoboard-coin-service
        - heroku container:release web -a cryptoboard-coin-service



