language: java
jdk:
  - openjdk16
services:
  - docker
before_install:
- chmod +x mvnw
addons:
  sonarcloud:
    organization: "dirklemmen"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
jobs:
  include:
    - stage: code_quality_check
      script:
        - sonar-scanner
    - stage: build_java_package
      script:
        - mvn clean package

    - stage: build_docker
      script:
        - docker build -f Dockerfile -t cryptoboard-coin-service:latest .
        - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag cryptoboard-coin-service "$DOCKER_HUB_USERNAME"/cryptoboard-coin-service
        - docker push "$DOCKER_HUB_USERNAME"/cryptoboard-coin-service